#!/bin/bash

# script/setup: Tells Docker to setup the project by configuring YAML config files
# & getting and building Docker images.

set -e

cd "$(dirname "$0")/.."

echo "===> Getting passwords from LastPass if available"
[ -f ./bin/lastpassify ] && [ -f ./config/database.example.yml ] && ./bin/lastpassify

echo "==> All done!"
